spring:
  application:
    name: nyamnyam_kr
  datasource:
    url: jdbc:mysql://localhost:3306/nyamnyam
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # ???? ??????? ??? ? ?? /resources/data.sql? ????? ??? ? ??
    hibernate.ddl-auto: update # Entity? ?? ??? ???? ???? ???? DDL??? ??? ? ? ?? ?? DDL ? ? ??? ??
    show-sql: true # SQL ?, Query? ??? ? ??
    properties:
      hibernate.format_sql: true # ??? ????? ??? ???? ??? ?????? ??
      hibernate.default_batch_fetch_size: 100 # JPA?? ?? ??? ??? ????? ??? ?? ?? ??? ???? ? ? ??? ???? ??? ? ??
    sql:
      init:
        mode: always
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 2MB
        max-file-size: 20M
        max-request-size: 20MB
    server:
      port: 8080