spring:
  application:
    name: nyamnyam_kr
  datasource:
    url: jdbc:mysql://223.130.131.65:3306/nyamnyamdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      default_batch_fetch_size: 100
    sql:
      init:
        mode: always
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 20MB
      max-request-size: 20MB
file:
  upload-dir: C:/Users/user/Documents/nyamnyam/uploads
server:
  port: 8080
