spring:
  data:
    mongodb:
      uri: mongodb://root:1234%21%40%23%24@211.188.50.33:27017/test
      auto-index-creation: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
    time-zone: UTC
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: e2iaB9q3A_kk1k7hX6Qi
            client-secret: Av6eAE_PsV
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me

server:
  port: 8081

jwt:
  secret:
    key: ${JWT_SECRET_KEY}  # 여기 비밀키를 설정하세요.
  validity:
    in:
      milliseconds: 3600000  # 유효성 기간을 설정하세요 (1시간).

naver:
  storage:
    accessKey: ncp_iam_BPASKR4hDZEqhZxoJTU0  # Naver Cloud Storage 접근 키
    secretKey: ncp_iam_BPKSKRW7EiCKxGGi0L9AODsJCwtJ8wcZ9a  # Naver Cloud Storage 비밀 키
    bucket: nyamnyam  # Naver Cloud Storage 버킷 이름
    upload:
      path: uploads/user  # 업로드 경로

logging:
  level:
    org.springframework.web: DEBUG
    kr.nyamnyam: DEBUG


