spring:
  data:
    mongodb:
      uri: mongodb://root:1234@211.188.50.33:27017/test
      auto-index-creation: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
    time-zone: UTC
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8081
naver:
  storage:
    accessKey: D5172C7FA5E1DA25C262
    secretKey: 42FB384E0E984E7CE8808626314BE69D52DAD1FC
    bucket: nyamnyam
    upload:
      path: uploads/chats



