spring:
  application:
    name: nyamnyam_kr
  datasource:
    url: jdbc:mysql://localhost:3306/nyamnyamdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      default_batch_fetch_size: 100
    sql:
      init:
        mode: always
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 20MB
      max-request-size: 20MB
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: e2iaB9q3A_kk1k7hX6Qi
            client-secret: Av6eAE_PsV
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/api/user/login/oauth2/code/naver
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response

server:
  port: 8080
