import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title> 냠냠! </title>
      </head>
      <body className={inter.className}>
      <div className="navbar">
        <a href="#home">홈</a>
        <a href="#about">소개</a>
        <a href="#services">서비스</a>
        <a href="#contact">연락처</a>
    </div>
        

        {children}
      </body>
    </html>
  );
}
